language: java
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
notifications:
  slack:
    secure: EZvH9cytnCFeoYE27+H4IQFrpejBsFVq+2ZXQToddK3ZNo3P2s+EtNj7GQX1lDDL5btsiwf7sKGpm9LvV8Zwf+pSnI+DMXwQWAuqjVPO2JSVlVSv+BszVhazzyV+6DpnzXMdbLEtCTNG/YQTkSF4DhYOCc1PLn4Ui+EQX2ZsBxaNRRMpR+HJ1IEg10h2p1/ICdDJq7mo3RnW0be9pS9uMcr+gDYCxZqF9uS/IHzNy4sW/7MOGAWLupD+0Ia+GVZjSbt9ShPfi82uk4S4OZPcQ92+pu5igZzkfVs+8/q1DMDjxN7NdjiLRbBs5gK7uMFz0IYNeQPo+yXu3zdgh9FrPM28xEuBKa+XTxaxxAjtDyZnWvS23csjEP0QzLgixMBy/H7GeVCtnGubRc2/ir+qF0u5sGXoW3agLuydjaU8X039UAVGIhl63TZIgL9NXtnQ14c5SvdGsBRDRvsB83Rc5YUfe3FfrzZYk/wEUJlATZquZJEQw1/thrH5JfxKYQOkMaC0pnLLS0Q4HFVhdZ33a6hfyltwud0iibFgo9YrfhIKysIiIpcFjFrnYW2k9+Mn+OJ4F1gaGKvtPDqpo+xVZpx8M46pC6dml+Fxo0/gCuor1DY7JkrQ6ddMEHR+awYIt+dY4TN4ao8TrGvQoySZZp3z8TmC8bq/YjWqhabvWsI=
